### ISSUE TITLE
Where is nnUNet_predict

### ISSUE THREAD

**Issue by parinazbabaee** [DCAN-Labs/BIBSnet-deprecated#9]
### What happened?

Hi!

I want to segment T1w and T2w images of an infant using BIBSnet. I already followed the instruction for naming the files. I downloaded the package, and I used the following command:

python3 run.py --input /Users/p/Desktop/data --output /Users/p/Desktop/data/seg --task 512 --nnUNet ? --model 3d_fullres

Here is the error message:

run.py: error: argument --nnUNet/-n: Cannot read file at '/Users/p/Documents/BIBSnet/nnUNet_predict'

But I don't know where I can find "nnUNet_predict".

I have already downloaded the "3d_fullres" package, and I fetched the "nnUNet" from the GuitHub using the following code:

git clone https://github.com/MIC-DKFZ/nnUNet.git
cd nnUNet
pip install -e .

but it didn't solve the problem.

Would you please help me to solve this issue?

Thank you in advance,
Parinaz.

### What command did you use?

```shell
python3 run.py --input /Users/p/Desktop/data --output /Users/p/Desktop/data/seg --task 512 --nnUNet ? --model 3d_fullres
```

### What version of BIBSnet are you using?

main

### Relevant log output

```shell
run.py: error: argument --nnUNet/-n: Cannot read file at '/Users/p/Documents/BIBSnet/nnUNet_predict'
```

### Add any additional information or context about the problem here.

I have already downloaded the "3d_fullres" package, and I fetched the "nnUNet" from the GuitHub using the following code:

git clone https://github.com/MIC-DKFZ/nnUNet.git
cd nnUNet
pip install -e .

But it didn't solve the problem.

**Comment by audreymhoughton** [comment]
Hi @parinazbabaee - I suggest you use: github.com/DCAN-Labs/CABINET to run BIBSnet for now, as its installs are more regularly maintained. I have an idea as to how to fix this within BIBSnet, but it might take a little while for my team to get it implemented. Thanks!

**Comment by parinazbabaee** [comment]
Thank you!
